# -*- coding: utf-8 -*-
"""DAP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12V54PqzbrBxhzjrCfHihhGJPhKYQzHRH
"""

import numpy as np
    #repeated

arr=np.array([1,2,3,4,5])
print(arr)
zeros_arr=np.zeros((3,3),dtype=int)
print(zeros_arr)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
b=pd.read_csv("/content/tempe.csv")
print(b)

avg_temp=b['temperature'].mean()
high_temp=b['temperature'].max()
low_temp=b['temperature'].min()
threshold=50
days_above_threshold=b[b['temperature']>threshold].shape[0]

print("Average temperature:",avg_temp)
print("Highest temperature:",high_temp)
print("Lowest temperature:",low_temp)
print("Number of days temperature exceeded",threshold,"degree celsius:",days_above_threshold)

b.plot(kind='line',color='green')
plt.title("Temperature for 50 days")
plt.xlabel("Days")
plt.ylabel("Temperature")

pip install seaborn

import seaborn as sns
import matplotlib.pyplot as plt
#load example dataset
tempe=sns.load_dataset("tips")
sns.scatterplot(x="total_bill",y="tip",data=tempe)
plt.title("scatter plot of total bill vs. tip")
plt.xlabel("total_bills")
plt.ylabel("tip")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
#load example dataset
tempe=sns.load_dataset("attention")
sns.violinplot(x="subject",y="score",data=tempe)
plt.title("scatter plot of subject vs. score")

plt.xlabel("subject")
plt.ylabel("score")
plt.show()

iris=sns.load_dataset("iris")
print(iris)
correlation_matrix=iris.corr()
sns.heatmap(correlation_matrix,annot=True,cmap="coolwarm")

iris=sns.load_dataset("attention")
print(iris)
correlation_matrix=iris.corr()
sns.heatmap(correlation_matrix,annot=True,cmap="coolwarm")

import

import seaborn as sns
import matplotlib.pyplot as plt
#load example dataset
t=sns.load_dataset("attention")
print(t)
sns.scatterplot(x="subject",y="score",data=t)
plt.title("scatter plot of subject vs. score")
plt.xlabel("subjects")
plt.ylabel("score")
plt.show()

import numpy as np
a=np.array([[2,4,5],[6,7,8]])
b=np.sum(a,axis=0)
d=np.sum(a,axis=1)
print(b)
print(d)

import numpy as np
new=np.loadtxt("/content/new.txt", dtype=int)
new=np.savetxt("/content/news.txt",new)
print(new)

import matplotlib.pyplot as plt
a=np.array([1,2,3,4])
plt.plot(a)

#pandas
import pandas as pd
a=["rupa","pavani","uma","mouni","sofia","jeshi","sathwik"]
r=pd.Series(a,index=[10,1,3,4,5,7,2])
print(r)

import pandas as pd
international_students=pd.read_csv("/content/international_students.csv")
print(international_students)
print(international_students.loc[1])



international

import pandas as pd
international_students=pd.read_csv("/content/international_students.csv")
print(international_students)
a=international_students['2021'].mean()
international_students=international_students.fillna(a)
print(a)
international_students=international_students.drop_duplicates()
print(international_students)
print(international_students.head(10))
print(international_students.tail(10)

import pandas as pd
international_students=pd.read_csv("/content/international_students.csv")
international_students.shape
a=international_students.tail(10)
b=international_students.head(10)
c=pd.concat([a,b])
c.to_csv("c.csv")



data=pd.read_csv("/content/data.txt",sep=",")
print(data)

from google.colab import drive
drive.mount('/content/drive')

print(c.groupby(["2021"])["2022"].count())

import pandas as pd
b=pd.read_csv("/content/international_students.csv")
print(b)

import matplotlib.pyplot as plt
a=[230,560,780,127,128]
b=[200,160,270,127,400]
years=[1,2,3,4]
profit_a=[(a[i]-a[i-1]) for i in range(1,len(a))]
profit_b=[(b[i]-b[i-1]) for i in range(1,len(b))]
plt.subplot(2,1,2)
plt.plot(years,profit_a,color='hotpink',linewidth='3',label='CompanyA',marker='*',ms='15',mec='c')
plt.subplot(2,1,1)
plt.plot(years,profit_b,color='black',linestyle='dotted',label='CompanyB',marker='H')

import numpy as np
import matplotlib.pyplot as plt
runs=np.array([100,50,91,78,89,25,34,19,9,10])
w=np.array([1,0,2,0,3,7,8,9,7,5])
plt.scatter(runs,w,color="orange")
plt.title("IND_vs_AUS__score")
plt.show()

import numpy as np
import matplotlib.pyplot as plt
#generating  between -pi to pi of array 200
tigar=np.linspace(-2*np.pi,2*np.pi,50)
print(tigar)
plt.plot(tigar,np.sin(tigar),color="black")#sin
#plt.plot(x,y,color,labels..)
plt.title("sin(x)")

import numpy as np
import matplotlib.pyplot as plt
overs=np.arange(5,50,5)
overs_a=np.arange(5,30,5)
runs_i=np.array([25,51,84,131,160,189,220,250,267])
runs_a=np.array([15,41,94,110,151])
wickets=np.array([12,32,96])
#plotting
plt.plot(overs,runs_i,color="blue",label="india")
plt.plot(overs_a,runs_a,color="yellow",label="aus")
plt.legend(loc="best")
plt.show()



a=np.array([25,60,5,10])
labe=['AIML','PYTHON','PANDAS','NUMPY']
plt.pie(a,labels=labe)
plt.show()

#explode
a=np.array([25,60,5,10])
labe=['AIML','PYTHON','PANDAS','NUMPY']
explo=[0.2,0,0,0]
plt.pie(a,labels=labe,explode=explo,colors=["yellow",'red','green','blue'],startangle=180,textprops={'fontsize':18})
plt.show()

grocery_store=pd.read_excel("/grocer_store.xlsx")
print(grocery_store)

from google.colab import drive
drive.mount("https://drive.google.com/file/d/1GY93PQK-H0i8xbT48jE4HQll_oGOmrvY/view?usp=drive_link")

import pandas as pd
grocery_store=pd.read_excel("/grocery.xlsx",sheet_name=0)
print(grocery_store)